### ISSUE TITLE
Correct output data

### ISSUE THREAD

**Issue by peterseetal14** [ij96/Honeywell_RSC#2]
Hi. Thank you for your contribution with this library.  I'm new to coding, so may be wrong with this. I've built my code around your example code, reading pressure data from multiple RSC pressure sensors. I'm reading out correct serial numbers, temperatures, etc. from the sensors, but the pressure values don't seem to be correct.  Some appear offset quite a lot, and others aren't changing at all.  I was curious whether the error is in my code or (respectfully) in your library.

I found a technical paper from Honeywell, where I couldn't identify this process in your cpp file (link below):
https://sensing.honeywell.com/auto-zero-calibration-technique-pressure-sensors-technical-note.pdf

In my code, I'm only additionally setting the data rate, compared to your example code and creating multiple instances of the class for my multiple sensors.  If I should be doing something in my code to auto-zero, I'd appreciate any advice.

Many thanks.

**Comment by jhynes94** [comment]
This library does not appear to be working for Arduino on the ADC side.

@peterseetal14 have you made further progress? When I'm reading out data it seems to be the same for temp as well as pressure.

**Comment by andyma56** [comment]
There is a simple error in the library, in setup_adc.

void Honeywell_RSC::setup_adc(uint8_t* adc_init_values) {
  // refer to datasheet section 3.4 ADC Programming Sequence – Power Up
  uint8_t command[5] = {RSC_ADC_RESET_COMMAND, adc_init_values[0], adc_init_values[1], adc_init_values[2], adc_init_values[3]};
  adc_write(0, 5, command);
  delay(5);
}

In adc_write there is check for number of bytes.

void Honeywell_RSC::adc_write(uint8_t reg, uint8_t num_bytes, uint8_t* data) {
  // check if the register and the number of bytes are valid
  // The number of bytes to write has to be - 1,2,3,4
  if (num_bytes <= 0 || num_bytes > 4)
    return;
	.
	.
	.

So actually there is no adc setup.

I changed setup_adc a little and got it to work.

void Honeywell_RSC::setup_adc(uint8_t* adc_init_values) {
  // refer to datasheet section 3.4 ADC Programming Sequence – Power Up
  uint8_t command[4] = {adc_init_values[0], adc_init_values[1], adc_init_values[2], adc_init_values[3]};
  
  select_adc();
  SPI.transfer(RSC_ADC_RESET_COMMAND);
  deselect_adc();

  adc_write(0, 4, command);
  delay(5);
}

**Comment by ij96** [comment]
Hi, thank you for letting me know about this issue. As @andyma56 pointed out, `setup_adc()` is trying to write 5 bytes, when `adc_write()` only allows 1 to 4 bytes to be written.

> void Honeywell_RSC::setup_adc(uint8_t* adc_init_values) {
>   // refer to datasheet section 3.4 ADC Programming Sequence – Power Up
>   uint8_t command[4] = {adc_init_values[0], adc_init_values[1], adc_init_values[2], adc_init_values[3]};
> 
>   select_adc();
>   SPI.transfer(RSC_ADC_RESET_COMMAND);
>   deselect_adc();
> 
>   adc_write(0, 4, command);
>   delay(5);
> }

@andyma56's solution looks good, thank you for sharing! If convenient, please feel free to create a pull request. Although unfortunately I no longer have the RSC sensor at hand, so I can't test this right now.

**Comment by michaelmeersman** [comment]
Hi, I seem to be having the same issue as @peterseetal14. I made the suggested fix above, but I'm still reading the same pressures as before. I have an array of sensors set up and each one is reading a different "zero" value. Any suggestions on why that might be?

**Comment by jhynes94** [comment]
Good catch! You're the man :)
